name: simple_edge_detection
description: A Flutter plugin enabling the user to detect edges of a given
  image. It returns the relative coordinates of the detection rectangle.
version: 0.0.1
homepage: https://www.flutterclutter.dev

environment:
  sdk: '>=2.15.0 <4.0.0'

dependencies:
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: dev.flutterclutter.simple_edge_detection
        pluginClass: SimpleEdgeDetectionPlugin
      ios:
        pluginClass: SimpleEdgeDetectionPlugin
